name: Android - Build & Publish Release APK - Development

on:
  push:
    branches: feature/update_ci
  # pull_request:
  #   branches: development

jobs:
    # Test:
    #   runs-on: ubuntu-latest
    #   steps:
    #     - uses: actions/checkout@v2
    #     - name: Install dependencies
    #       run: npm install --legacy-peer-deps
    #     - name: Run Jests tests
    #       run: npm run test  

    Gradle:
        # needs: test
        runs-on: ubuntu-latest
   
        steps:
            - name: Checkout source code
              uses: actions/checkout@v2

            - name: Set up JDK 17
              uses: actions/setup-java@v1
              with:
                  java-version: 17

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 16

            - name: Install dependencies
              run: npm install --legacy-peer-deps

            - name: Build Android App Bundle
              run: |
                cd android && ./gradlew assembleRelease --no-daemon && cd ..
              env:
                GIPHY_API_KEY: ${{ secrets.GIPHY_API_KEY }}
                GIPHY_PATH: ${{ secrets.GIPHY_PATH }}
                TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
                TMDB_PATH: ${{ secrets.TMDB_PATH }}
                API_LINK: ${{ secrets.API_LINK_DEV }}

            - name: Cache Gradle
              uses: actions/cache@v2
              with:
                path: ~/.gradle/caches/modules-2
                key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
                restore-keys: |
                  ${{ runner.os }}-gradle-

            - name: Cache Gradle Wrapper
              uses: actions/cache@v2
              with:
                path: ~/.gradle/wrapper
                key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

            - name: Cache Gradle Dependencies
              uses: actions/cache@v2
              with:
                path: ~/.gradle/caches
                key: ${{ runner.os }}-gradle-caches-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
                restore-keys: |
                    ${{ runner.os }}-gradle-caches-
        
            - name: Make Gradlew Executable
              run: cd android && chmod +x ./gradlew
            
            



            # - name: Debug Keystore
            #   run: |
            #     ls -R android/app/build/outputs/bundle/release
            #     echo "Contents of keystore directory:"
            #     # ls -l ${{ secrets.KEYSTORE_PATH }}

            - name: Sign Android release   
              id: sign_app
              uses: r0adkll/sign-android-release@v1
              with: 
                releaseDirectory: app/build/outputs/bundle/release
                signingKeyBase64: ${{ secrets.KEYSTORE_PATH }}
                signingKeyPassword: ${{ secrets.KEYSTORE_PASSWORD }}
                signingKeyAlias: ${{ secrets.KEY_ALIAS }}
                signingKeyAliasPassword: ${{ secrets.KEY_PASSWORD }}

            - name: Publish Release APK
              uses: actions/upload-artifact@v3.1.3
              with:
                name: peelApp.apk
                path: ${{ steps.sign_app.outputs.signedBundlePath }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KEYSTORE_PATH: ${{ secrets.KEYSTORE_PATH }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          APP_FOLDER: app
